name: Build DevContainer Image

on:
  push:
    branches: [ main, master ]
    paths:
      - '.devcontainer/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/jecarrique/ros2-esp32-c3/devcontainer
          subFolder: .
          push: 'always'
